version: "3.8"

services:
  app:
    image: roulage/istatdb:2025-07-24-10-03
    container_name: istatdb-app
    ports:
      - "3000:3000"   # adjust if your app runs on a different port
    environment:
      - RAILS_ENV=production  # or RAILS_ENV, depending on the app
#    volumes:
#      - .:/app         # optional: mount local code into container
#      - sqlite_data:/app/db
#    command: bash -c "bundle install && ruby app.rb"  # adjust to your app's entrypoint
