# config/app.yml for rails-settings-cached
defaults: &defaults

  backup_adress: "0.0.0.0"
  backup_port: 24
  backup_user: "admin"
  backup_pass: "0000"
  backup_root: "~/istatdb-backup/"
  backup_enabled: "0"

  valuts_adress_history: "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml"
  valuts_adress_daily: "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
